### ISSUE TITLE
Alternative suggestions - Nearest Neighbours

### ISSUE THREAD

**Issue by smcdufff** [awslabs/sockeye#179]
Hi,

I'm looking  to find alternative translation where the user would be able to change words in the translated sentence.

Here an example: English to French
"I love apples." -> "J'aimes les pommes."

The user could be able to click over "aimes" and see others possibilities like "adores","..", etc..
When the user change the word, the sentence needs to be retranslated given the choice the user submitted..
2 challenges:
1- Nearest neighbour of "aimes" given the context of the sentence "I love apples." 
2- Also, how to recalculate words given some words we NEED to use ?
 ex: I love apples -> J'adores ..... 
Any advice where to start ? 

Simon

**Comment by fhieber** [comment]
Sorry for the late response and thanks for your interest in Sockeye.

My first idea would be return not only the 1-best translation from Translator::translate in inference.py but return an n-best list, but you probably won't get too much variation there since it's a fairly small beam typically.

The right thing would be to redecode a suffix, given a prefix when the user changes a word. The 'nearest neighbours', or most probable alternatives to the chosen word you always get from the decoder at every time step.

In any case, this probably involves quite a bit of engineering. You could start by taking an InferenceModel, implement a simple greedy search (always picking the best word at every time step), while saving the ranked list of alternatives.
