### ISSUE TITLE
 Initialize embedding weights with pretrained word representations

### ISSUE THREAD

**Issue by xingniu** [awslabs/sockeye#231]
In order to initialize Sockeye embedding weights with pretrained word representations, I am thinking to:
1. Pretrain word representations using Corpus-A and get `Embed-A` and `Vocab-A`.
2. Create the vocabulary of Corpus-B which will be used for NMT, i.e. `Vocab-B`. (Using sockeye-vocab)
3. `Embed-A`, `Vocab-A`, `Vocab-B` -> `Embed-B`.
3.1. Load `Embed-A` and `Vocab-A`;
3.2. Create `Embed-B` with random values;
3.3. Copy word representations from `Embed-A` to `Embed-B` for overlaps between `Vocab-A` and `Vocab-B`.
3.4. Store `Embed-B` in the format of `Dict[str, mx.nd.NDArray]`, str can be for example "target_embed_weight".
4. Start Sockeye training by loading `Embed-B` with model parameter `--params`.

Is this workflow correct? If so I can create a tool to do Step 3.

**Comment by fhieber** [comment]
Sounds like a good approach!
One issue you may encounter is that if you try starting training with `--params` and this file does not include all parameters required by the model, it will fail due to the `allow-missing=False` in this [line](https://github.com/awslabs/sockeye/blob/master/sockeye/training.py#L249).
You could add another flag to the training cli that overrides this explicitly to support your use case, e.g. something like `--allow-missing-params`. In that case `{source,target}_embed_weight` would be initialized from your file, and the rest initialized with the random initializers from MXNet.

**Comment by xingniu** [comment]
Thanks for the hint! I will be working on this.
