### ISSUE TITLE
smallest_k_mx just partitions but does not sort

### ISSUE THREAD

**Issue by tdomhan** [awslabs/sockeye#270]
Writing this done before I forget about it: _beam_search expects the first hypothesis to be the best hypothesis (see `_get_best_from_beam`). The function `utils.smallest_k` guarantees this by sorting the partition returned by numpy. `smallest_k_mx` does not, as it takes the output of mxnet's `topk`. Right now this is not an issue because 1. `smallest_k_mx` is not used and 2. mxnet's `topk` actually sorts. However, we can not rely on a concrete implementation of `topk` and should change `smallest_k_mx` accordingly..

**Comment by sxjscience** [comment]
The implementation in mxnet.topk is to first sort and the take the top k elements and should be fine to use.

**Comment by tdomhan** [comment]
that makes sense. I guess the question is though, whether this is the guaranteed behavior of topk, order whether this is a side effect of the current implementation?

**Comment by mjpost** [comment]
I see. Looking at [the documentation](https://mxnet.incubator.apache.org/api/python/symbol.html#mxnet.symbol.topk), no guarantee is made that the top `k` elements will be sorted, so MXNet's `topk` actually only guarantees something similar to numpy's `argpartitiion()`. This might just be an error with the documentation, though. Perhaps we could get a clarification?

**Comment by tdomhan** [comment]
yeah, so I think we either need to update the documentation around guarantees in mxnet or add a second sorting step in smallest_k_mx just to make sure future changes to topk won't break our beam search.

**Comment by sxjscience** [comment]
@tdomhan It's currently the side effect of the implementation. Sorting after topk is a good solution. Another solution is to combine slice_axis and sort:
```python
out = nd.slice_axis(nd.sort(data, axis=-1), axis=-1, begin=0, end=K)
```

**Comment by mjpost** [comment]
What about just leaving it like it is until the topk() in MXNet is updated? I think our test cases would catch a situation where this gets updated without us noticing. My speed tests (which I'll post tomorrow) show much better performance of topk() on both p2's and p3's, but *much worse* performance on CPU's.

Alternately, we could use @sxjscience's proposal here (slice + sort) and then revert to topk() when it is no longer sorting.

**Comment by sxjscience** [comment]
@mjpost Great! I can later help submit a feature request in MXNet quoting the speed tests.

**Comment by mjpost** [comment]
Okay, I just posted [some timing experiments on a PR](https://github.com/awslabs/sockeye/pull/230#issuecomment-375263091) that show that MXNet's topk() is faster than using numpy's, for both P2 and P3 instances, at least for beam size >= 5.

**Comment by fhieber** [comment]
Thanks @mjpost , this is pretty convincing that we should use mxnet's topk for gpu contexts, and numpy's topk for cpu context (e.g. if `--use-cpu` is given on the translate CLI)! Would you be able to create a separate PR for this switch maybe?

On a related note, the mxnet topk function (https://github.com/awslabs/sockeye/blob/master/sockeye/utils.py#L284) still converts the topk results to numpy for unraveling the indices (getting the coordinates in the original `matrix` tensor. 
@sxjscience  do you think it would make sense to create a feature request to have such operator in mxnet? mshadow already seems to have it but it is not exposed to MXNet. I don't know how much work this would be but we would remove any dependency on Numpy in beam search here, and hence synchronization points between GPU and CPU due to no more `.asnumpy()` calls. This could give us another boost.

**Comment by mjpost** [comment]
Here are the graphs for CPU. MXNet is about 3x slower.

![beam_search_cpu](https://user-images.githubusercontent.com/455256/37780245-a2da1800-2dee-11e8-8134-3fb9196f8542.png)

**Comment by mjpost** [comment]
So I suggest we close this issue, and just keep in mind that if MXNet fixes its topk() implementation, we need to update to make sure they're sorted.
