### ISSUE TITLE
Performance comparison between training and translation

### ISSUE THREAD

**Issue by wsokolow** [awslabs/sockeye#420]
Hi guys.

Actually I'm running Sockeye with WMT_German_to_English dataset. I would like to compare performance of training vs inference (translation). Training mode returns "samples/sec" metric, while translation returns "sent/sec" metric. Is there any way to compare those two metrics? Or maybe modify translation's output to also provide "samples/s" value?

Best regards,
Wadim

**Comment by fhieber** [comment]
Hi @wsokolow,

samples/sec in training corresponds to the number of sentences per second processed in (sentence- or word-based) batches during training (including the time taken for the update). 
By increasing the batch size, this can be increased trivially (while decreasing updates/sec).
sent/sec in translation corresponds to the number of sentences per second translated. If using batch_size > 1, batches always correspond to sentence-based batches.
If you use word-based batching during training, I would say you cannot really compare two values. 

What we are not reporting at translation time is the average time for a beam search step, i.e. prediction of the next word (for the current sentence or the current sentence batch). This might be useful to have, but I am not sure if we should add this as we are moving towards a beam search implementation that is entirely run by imperative MXNet operations which are evaluated asynchronously. For proper timing of each step, one would have to add `mx.nd.waitall()`'s at the end of an iteration, which might slow down overall decoding speed.

**Comment by wsokolow** [comment]
Thanks for your kind answer @fhieber.

Looks like I'm using sentence-batching for training (batch_type='sentence', this is the default setting). So I assume that samples/s correspond to sentences/s.
The output from training looks like this:
```
[INFO:sockeye.training] Epoch[0] Batch [50]	Speed: 29.37 samples/sec 875.37 tokens/sec	perplexity=2733.850517
[INFO:sockeye.training] Epoch[0] Batch [100]	Speed: 31.02 samples/sec 856.14 tokens/sec	perplexity=1684.272067
[INFO:sockeye.training] Epoch[0] Batch [150]	Speed: 27.86 samples/sec 841.51 tokens/sec	perplexity=1351.840971
[INFO:sockeye.training] Epoch[0] Batch [200]	Speed: 33.50 samples/sec 850.91 tokens/sec	perplexity=1185.916501
```

Here is the log for the translation (same configuration, batches etc.):
```
[INFO:__main__] Translating...
[INFO:__main__] Processed 2999 lines in 47 batches. Total time: 714.5709, sec/sent: 0.2383, sent/sec: 4.1969
```

Looks like it's ~30 sent/s on training vs ~4 sent/s on translation... I would assume that translation should be faster than the training.



About the batches part, ideally I would like to compare training vs translation with different batchsizes (1,2,4,8.. 64 etc.).

Also, I can see an argument like this:
``` eval_params.add_argument('--sentence', '-s',action="store_true", help="Show sentence-level metrics. Default: %(default)s.")```
Maybe this is something that might help me?

**Comment by fhieber** [comment]
Hi @wsokolow,

Be aware that we recently changed the default batch type to `word`; if you update sockeye to the latest version your default might change.

Yes, your comparison looks fine, but I wouldn't share your hypothesis that translation should be faster than training. In training, you use teacher forcing and thus can 'unroll' the computation over the entire target sequence. Especially for models like the Transformer this gives you heavily parallelized and fast computation, leading to high throughput.
In translation you have to do beam search and because of that additional logic, the computation is currently not pre-defined as in training. This is why we use the imperative API of MXNet there.
It is not surprising that translation is slower than training.

The argument you are referring to is just for evaluation of quality metrics (BLEU, Chrf). By default BLEU is a corpus-level metric, but you can use this flag to make `sockeye.evaluate` return sentence-level BLEU scores (smoothed).

**Comment by wsokolow** [comment]
Thanks for all the explanation! You made things clear.

**Comment by tdomhan** [comment]
forward of modules will just run the computation graph, where the model is fed the reference tokens (instead of it's own predictions). As the full target side is known in advance this is very fast. Inference refers to the beam search (so the search over different output sequences) as implemented in `inference.py`. I hope that makes it clearer.

**Comment by tdomhan** [comment]
closing for now.
