### ISSUE TITLE
How to create a stacked Bi-LSTM encoder in training?

### ISSUE THREAD

**Issue by abaheti95** [awslabs/sockeye#436]
Couldn't find anything in the arguments.py file.

**Comment by tdomhan** [comment]
Currently the rnn encoder is limited to a single layer birnn followed by several rnn layers. The specification of encoders and decoders will become more flexible in the future though.

**Comment by abaheti95** [comment]
So how do you enable single birnn in the first layer?

**Comment by sawsanq** [comment]
Hello 

In the current implementation, do we have a stacked bidirectional LSTM layers or this is still a limitation?

**Comment by fhieber** [comment]
Implementation hasn't changed since the closing of this issue: the first layer is a bidirectional RNN with 50% of capacity for each direction, all the remaining layers in the encoder are unidirectional. If you want to change that you can change this line, https://github.com/awslabs/sockeye/blob/master/sockeye/encoder.py#L167, to use a `BiDirectionalRNNEncoder` encoder instead.
