### ISSUE TITLE
Exporting models

### ISSUE THREAD

**Issue by yx3zhang** [awslabs/sockeye#445]
Hi, is it possible to export the model in a single json + param format for mxnet to consume directly? 

I see the approach taken here seems to be outputting a params and json file but it cannot be consumed directly, it has to be read, bucketed, duplicate certain layers etc by InferenceModel class + its supers.

**Comment by tdomhan** [comment]
The reason you can not do this unlike say a classification model is that we run beam search at inference time which works by creating separate graphs for the encoder module and a single decoder time step. The target sequence generated is variable length so that you can not export it to a fixed size graph.
