### ISSUE TITLE
hypotheses lengths off by one

### ISSUE THREAD

**Issue by fhieber** [awslabs/sockeye#483]
It seems that the current beam search implementation (`_beam_search`) does not compute hypotheses length correctly. This can be seen when printing `sequences` and `lengths` just before returning from `_beam_search()`: the length is always one short of the actual non-zero values in sequences:

```
> sequences[0]
[    2    92  7741   907  2710   295    28     7  7741   907  2710     4
     7   383 10174  7324  9735   286   671   564  4085    71    22    98
 10671     4    13   782   485     8  6323  8665     4     8    23     8
  2976  1037  2448  3577    10   294   575  4664    13    34  3898   608
    43     5     3     0]
<NDArray 52 @cpu(0)>

> lengths[0]
[50.]
<NDArray 1 @cpu(0)>
```
`3` is the EOS id and the length of this hypothesis is clearly 51.

Let me try to explain the problem below. In practice, it doesn't matter since `_assemble_translation()` uses the length value to cut off the EOS symbol; the following EOS stripping logic in `_make_result()` is then redundant. But of course it shouldn't be and I think `_beam_search()` should return consistent data structures.

Here's the issue; I think this was introduced with length normalization only done for finished hypotheses:
1. `lengths` is initialized with 1s to account for the initial data in sequences, namely the BOS symbol
2. In each beam search iteration: as soon as we run topk on hypotheses scores, we effectively have expanded an hypothesis and its length increases by 1.
3. However, we are not using the updated length to potentially normalize the hypothesis if its finished. We check the newly acquired best_word_indices for EOS/PAD to compute a current `finished` status, and if so, **we normalize with the OLD length**.
4. This doesn't yet explain why we end beam_search with a length off by 1. This must somehow happen because the `length` array is only updated for hypotheses that are not finished and active. Since `finished` was just recomputed in step 3, the problem must lie in the `inactive` logic or the fact that right after we update `lengths`, we recompute `finished` once again and determine breaking out of the beam search loop based on that.

I am not 100% sure whats wrong here, probably the order of operations isn't entirely correct, but I also don't fully understand the whole `inactive` logic introduced. @mjpost could you comment on this?

At a minimum, we should make sure to normalize with correct length values. At best, we should make sure to return a `lengths` array from `_beam_search` that is consistent with `sequences`. With that, `_assemble_translation` would not silently cut off the last token (EOS), which by design should be handled later by `_make_result()`.

**Comment by mjpost** [comment]
From looking at the code, I think the problem is:

- We normalize finished hypotheses, and then update the set of finished hypotheses.
- This prevents lengths from being updated.

I think it might be sufficient to:

- Return `all_finished` from the `NormalizeFinishedHypotheses` hybrid block (as is currently done, though without the extra variable assignment)
- In the calling block, save that to a new variable instead of overwriting `finished`. This value will then be used for pruning.

With that, the updating of lengths should work correctly because `finished` itself will not have been updated yet.

I should be able to look at this soon but thought I'd document this here in the meantime in case someone else wants to fix it.

**Comment by mjpost** [comment]
Looking further, it seems we could eliminate the `UpdateLengthsAndFinished` hybrid block, and simply combine the two new blocks into a single block, done just before beam pruning.

**Comment by mjpost** [comment]
Okay, I fixed this. You can run a simple test and you see at the end that `sequences[0]` and `lengths[0]` are now corrected. The tests pass but style check will fail because of pylint issue #478.

**Comment by tdomhan** [comment]
Are we sure the length calculations haven't always been like this?

To me the lengths should be the length of symbols, which have been generated. In the sequences NDArray we include the <s> symbol, however it is not a symbol that gets generated by the model and it should therefore not count towards the length. That said, it would maybe be more consistent to return the sequences NDArray without <s>. With this in mind the length in the example given below is correct though if we discount for `0` and `2`.

For beam search I think it is actually the correct thing to use the old lengths array for normalizing for the fact that the lengths array is initialized to `1` instead of `0`. After generating the first real symbol we should normalize the score by `length_penalty(1)` as we have only produced a single score thus far.

So I think if we use the old lengths array we are doing the correct thing. That said, it is currently inconsistent and confusing what we do, so that there is potential for some refactoring/cleanup (that however should not change the way we score).

**Comment by mjpost** [comment]
Okay, I think I agree that we should not include `<s>` in the length counts. The principle can be that we only count steps actually generated by the decoder. But I don't feel strongly about it.

I think the other simplification I did can remain independent of this decision.

**Comment by tdomhan** [comment]
sounds good. Let's have the simplification, but not count the `<s>` for lengths and make sure that the returned values from `_beam_search` are consistent, e.g. by removing `<s>` before returning.

**Comment by fhieber** [comment]
@tdomhan your argument makes sense to me. The main reason I came across this is that it is a bit strange that we return `sequences` from `beam_search` with `lengths` not matching the actual sequences in there, then removing `</s>` in `_assemble_translation()` by using that length information, and finally remove the `<s>` token in `_make_result()` using the `self.strip_ids` logic.

**Comment by tdomhan** [comment]
Yes, so I think we did the correct thing the way we normalized with the lengths, however what we passed around was inconsistent and confusing.

**Comment by mjpost** [comment]
Okay, I just pushed up a version rebased on master that does all of this. This simplifies a lot of logic where we have to add a null column or strip it off when concatenating. It should be ready to go.

**Comment by tdomhan** [comment]
great, thanks!
