### ISSUE TITLE
Understanding weight initialization parameters

### ISSUE THREAD

**Issue by lambdaofgod** [awslabs/sockeye#617]
1) What is [default initializer](https://github.com/awslabs/sockeye/blob/master/sockeye/initializer.py#L41)? Does it initialize everything else than hidden-to-hidden and embedding weights?

2) Can I change default/embedding/hidden initializer with extra_initializers? How do I do that?

Specifically I want to initialize weights in hidden-to-hidden matrix with uniform distribution on [0, scale], and everything else with normal distribution with given std. Can I do that using extra_initializers?

**Comment by fhieber** [comment]
Yes, the default initializer applies to all parameters (as defined by the name pattern '.*') that are not covered by the other initializers (which have more specific name patterns). There are two specific initializers for
- Embedding weights (e.g. source_embed_weight, target_embed_weight, source_target_embed_weight)
- RNN internal parameters (".*h2h.*")

In the definition of the MixedInitializer, these specific pattern come BEFORE the default_init.
`extra_initializers` allows passing any additional set of initializers to the `MixedInitializer` which would override the ones described above.

`extra_initializers` should be of type `List[Tuple[str, mx.initializer.Initializer]]`, for example `my_extra_inits = [(".*h2h.*", mx.init.Uniform()), (".*", mx.init.Normal()))]`

This should work, because `MixedInitializer` uses the initializer whose pattern matches FIRST on a given parameter name when initializing later. That is, patterns that occur in `extra_initializers` and for example `rnn_init`, will be initialized with the one defined in `extra_initializers`.

**Comment by fhieber** [comment]
Closing for now, feel free to reopen if you have more questions.
