### ISSUE TITLE
The output of attention weight

### ISSUE THREAD

**Issue by tanggongbo** [awslabs/sockeye#637]
Hi,

I found an error in Sockeye when generating the attention distribution during inference. The sum of attention weights is not equal to 1. 

I found this problem in version 1.18.56. Then I tried 1.18.1 and it outputs the correct weights (sum to 1). I suspect that this problem is introduced since version 1.18.12 which adds 'eos' tag. I tried version 1.18.13 and it also outputs the incorrect distribution (not sum to 1). 

In addition, I tried to revise the configuration "source_with_eos: true" to "source_with_eos: false" in the config file. Then the attention weights sum to 1 which is reasonable. However, the BLEU score has a drop with this change.

**Comment by mjpost** [comment]
Sockeye adds an internal `</s>` to the input, and target words can attend to this symbol---in fact, the purpose of adding the symbol is so that the model will attend to it, instead of to sentence-final punctuation, which may not always be there. However, we strip this off from both the generated string and the attention weights. Probably this is not the right thing to do, at least for attention weights.

**Comment by tdomhan** [comment]
Thanks for reporting. For the attention matrix this indeed does not seem like the expected behavior and we should change the matrix to include the `</s>` symbol.
