### ISSUE TITLE
Motivation for supporting three architectures

### ISSUE THREAD

**Issue by ArmageddonKnight** [awslabs/sockeye#678]
Hi,

I have some general questions regarding the Sockeye toolkit.

- Why did you decide to implement all the three architectures (RNN, CNN, Self-Attention)? Especially given that Transformer has been proven to be superior in many NMT tasks. May I know what are the major advantages/disadvantages of those three architectures?
- Would you continue to support all the three architectures in the future?
- I am hoping to doing some performance benchmarking analysis on the three architectures. I saw that you have the `arxiv_1217` branch which contains the training and testing scripts. Is that branch still up-to-date? Or should I take the most up-to-date stable release instead.

Thank you so much for your precious time.

**Comment by fhieber** [comment]
Hi,

Having all three architectures in a single toolkit is useful for experimentation and research. Sockeye was one of the first toolkits to support all three common architectures for seq2seq modeling in 2017. When we started Sockeye, the transformer didn't exist yet; it was added only after a couple of months.
Right now we are offering full support for all three architectures as we ensure that all tests are passing with every commit. Going forward, we may prune features at some point, because they increase the complexity of the codebase considerably and are rarely used anymore these days.
The `arxiv_1217` branch is quote old but reflect the state of the toolkit when we published our Arxiv paper and makes the experiments there reproducible.
If you want an up-to-date benchmark you should use latest master.

**Comment by ArmageddonKnight** [comment]
Thank you so much for your reply.

Just curious. Is RNN still used in NMT these days? Especially since it is less efficient and effective compared with Transformer.

**Comment by fhieber** [comment]
Recurrent architectures still have their place in sequence modeling in my opinion.
As for efficiency at inference time, RNNs are actually not that bad, since they have a constant state size across time, whereas transformers with (unlimited) self-attention can be less efficient there.

**Comment by ArmageddonKnight** [comment]
Thanks a lot for answering my questions.
