### ISSUE TITLE
Slow speed with constrained decoding

### ISSUE THREAD

**Issue by okgrammer** [awslabs/sockeye#732]
Hello, I am trying the constrained decoding feature and noticed a big drop in decoding speed. I trained my model using the sockeye autopilot on WMT'14 en-de.

This is the initial speed without constrained decoding on 10 sample input sentences. The following command is taken from sockeye-autopilot:

```
cat input.src \
| python -m sockeye.translate --models=model.transformer --beam-size=5 --batch-size=32 --chunk-size=1000 --length-penalty-alpha=0.1 --length-penalty-beta=0.0 --max-output-length-num-stds=2 --bucket-width=10
... 
[INFO:__main__] Processed 10 lines. Total time: 1.8731, sec/sent: 0.1873, sent/sec: 5.3387
```

To test the constrained decoding, I put constraints for every capitalized word in the input (tab-separated like the sample in the docs), then I ran the same command from the docs (inference.md):

```
cat input.constrained.src \
| python -m sockeye.lexical_constraints \
| python -m sockeye.translate --models=model.transformer --beam-size=20 --beam-prune=20 --json-input
...
[INFO:__main__] Processed 10 lines. Total time: 28.8328, sec/sent: 2.8833, sent/sec: 0.3468
```

Both commands were run on a GPU. As seen above, the speed dropped significantly. If I included the other args (length penalty etc.), the decoding became even slower, 30 sec/sent. Even with a smaller beam size (5, 10) the speed is still much lower than the original decoding speed. I am wondering if this is expected, or if I have missed something in the constrained decoding usage.

**Comment by mjpost** [comment]
Yes, constrained decoding is slow, though the overhead I usually see is 3–5x, and not the amount you're seeing here. It may be that recent changes with Sockeye made it even slower, since I think it's a feature that's not being actively maintained.

We have some improvements that are not in the main Sockeye branch, for example that make it work with batching. It also seems to improve over the Sockeye implementation when not batching, since the beam allocation is done in a matrix-oriented fashion instead of a logical one. See:

- the paper: https://www.aclweb.org/anthology/N19-1090/
- the branch: https://github.com/edwdh/sockeye/tree/trie_constraints
