### ISSUE TITLE
Question: Sockeye 2.1.16 training - use of GPU 0

### ISSUE THREAD

**Issue by tuglat** [awslabs/sockeye#868]
Each of my training processes seem to want to have some presence on GPU 0, even though their main processing is on another GPU. Why is that?

If I have a non sockeye process on GPU 0, then sockeye training on GPU 1 (for example) will die w/ GPU out of memory. If there is a sockeye training process on GPU 0, then sockeye training on GPU 1 will proceed happily, w/ no parameter changes.

**Comment by mjdenkowski** [comment]
We've observed some corner cases with MXNet's multi-GPU mode.  If you install Horovod (`pip install -r requirements/requirements.horovod.txt` or use the GPU [Docker image](https://github.com/awslabs/sockeye/tree/master/sockeye_contrib/docker)), you can run multi-process training where each Sockeye process will use strictly one GPU.  Results should be comparable to single-process multi-GPU training.

You can run multi-process training with `horovodrun -np N python3 -m sockeye.train --horovod --device-ids -1 ...` where `N` is the number of processes/GPUs.  Sockeye will use GPUs `0`-`N-1`.  Batch size is also per-process, so if you're currently using 4 GPUs with batch size 8192, you would specify a batch size of 2048 when using Horovod.

**Comment by tuglat** [comment]
thanks, I'll git it a try.

**Comment by graftim** [comment]
Another possibility to work around this issue without needing horovod is to also use the docker GPU image, and starting the container with `--gpus '"2,4"'` if you want to use gpus 2 and 4. Note that you need to use single AND double quotes around the gpu-ids. For training inside the container, you will then need to set `--device-ids 0 1`, because the id's in the container start at 0 again.
