### ISSUE TITLE
Projection layer 

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#877]
Hi @fhieber, in Model.py, 

self.output_layer = layers.OutputLayer(hidden_size=self.decoder.get_num_hidden(),
                                                   vocab_size=self.config.vocab_target_size,
                                                   weight=self.output_weight, dtype=config.dtype)

Is there a way to add another projection layer to the output layer to make it more adaptable to different vocab size? 

What is the command for building a output layer when it consists of multiple internal layers? 

Really appreciate your input, thank you so much!

**Comment by bricksdont** [comment]
As far as I can see, the code currently does not support multi-layer `OutputLayer` objects.

What do you mean by making this layer more adaptable to different vocab sizes?

The code already instantiates an output layer that projects correctly to any output vocabulary size.

**Comment by i55code** [comment]
@bricksdont, thank you for your reply! 

To elaborate on making the output layer more adaptable to different vocab size, I am thinking of a hypothetical case to finetune an existing model on a new dataset (which has a different vocab size than the existing one). The one on the Sockeye documentation specifies the existing vocab in finetuning the new one. I wonder whether there is a way to extend its application to cover the cases when the two vocab size differs. 

Please let me know which part of the code to start changing to make it happen, if it is not already done before. Thanks!

**Comment by bricksdont** [comment]
Making the output layer a multilayer network does not make it easier to finetune a model that was pretrained with a different vocabulary, in my opinion. You would need to elaborate on this a bit more and it would be helpful if you could mention _why_ those models cannot have the same vocabulary.

Additional thoughts:

If the vocabularies for pretraining and finetuning are different, then it is less clear how to benefit from pretraining. For instance, regarding embeddings:
- during pretraining you might have learned reliable embeddings, but if the vocabulary items associated with those embedding vectors are not in the finetuning vocabulary, then they will never be used or updated at all.
- if finetuning introduces a new vocabulary item, then the initial embeddings for it will be random instead of pretrained.

Also, the output layer can be tied with one or both embedding matrices - and weight tying is used very often. If it were a multilayer network, then which part would share weights with the embedding layers?

**Comment by i55code** [comment]
Hi @bricksdont , thank you for your reply, I do think the points you raised are true and very important, but I am curious to see the results of building a multilayer output layer. I would appreciate some pointers on how to change the code for the output layer. 

For weight tying, sharing the weights with the first layer of the output layer interfacing with the decoder would be good enough. 

Thank you!
