### ISSUE TITLE
[Question] Is there a way to set different batch size for train and validation? 

### ISSUE THREAD

**Issue by sianvolta** [awslabs/sockeye#908]
Is there a way to set different batch size for train and validation? 

Looking at https://github.com/awslabs/sockeye/blob/6e9dba6be750cec08129e6242c52283bc8533848/sockeye/train.py#L303, there's no clear example to set different `batch_size` values for training and validation.

**Comment by bricksdont** [comment]
There is no command line argument to configure validation batch size, it is set to 16 since that is the default value here:

https://github.com/awslabs/sockeye/blob/master/sockeye/checkpoint_decoder.py#L73

The `CheckpointDecoder` class has a `batch_size` argument you could set yourself as a quick solution.

**Comment by tdomhan** [comment]
That's right, we don't currently expose this via the CLI.
Is there a particular reason why you'd like to change the batch size?

Also we'd be happy to merge any PR to expose this :)
