### ISSUE TITLE
Install version 2.2.7

### ISSUE THREAD

**Issue by michaelhochleitner** [awslabs/sockeye#927]
I have a model trained with version 2.2.7. I'm trying to install 2.2.7 since the major code version has to match.[1,2] There is no tag for 2.2.7 in https://github.com/awslabs/sockeye/tags and https://pypi.org/project/sockeye/#history. Is there a way to install 2.2.7?

[1] https://github.com/awslabs/sockeye/issues/793
[2] https://github.com/awslabs/sockeye/issues/916

**Comment by tdomhan** [comment]
It's correct that the major version needs to match. If you are using 2.2.x then from the versions with a tag you could use any under 2.2.x. Using the latest probably makes sense so that would be 2.2.8 (`pip install sockeye==2.2.8`). 
If you need the specific minor version, 2.2.7, then that would be commit 3736f18e3286895cb1eb29817396a8b508edd802.
